name: CapTheFlag
version: 1.0
author: _xGQD
main: me._xGQD.CapTheFlag.Main
description: Duels Plugin

commands:
  ctf:
    aliases: []
    description: This is the ctf command!

permissions:
  captheflag.*:
    default: false
  captheflag.play: 
    default: true
    